name: dox
description: A dox cli to create model, migration with dox_query_builder
version: 1.0.49
homepage: https://www.dartondox.dev/

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  dox_query_builder: ^1.1.3
  postgres: ^2.6.1
  dox_core: ^0.0.2
  watcher: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  dox: dox
