name: dox
description: A dox cli to create model, migration with dox_query_builder
version: 1.0.35
homepage: https://dox.zinkyawkyaw.dev

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dox_query_builder: ^1.0.0
  postgres: ^2.6.1
  dox_core: ^0.0.2
  watcher: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  dox: dox
