name: dox
description: A dox cli to create model, migration with sql_query_builder
version: 1.0.7
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  sql_query_builder: ^1.0.12
  postgres: ^2.6.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  dox: dox
